title: Projects By Basma
author: Basma Mohammed 
email: basma.mohammed1@ocsbstudent.ca
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my GitHub page. I Am a student who is passionate about programming.
 On this site, you'll be able to see some of my awesome projects. 
 
# social links
github_username:  basma2002

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
